I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 192, in script call
    call fixBug(doc, 3, "64", "$ turn = \"x\"")
  File "game/fixBug.rpy", line 22, in script
    player "Hold on-- that's not it."
Exception: Sayer 'player' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 192, in script call
    call fixBug(doc, 3, "64", "$ turn = \"x\"")
  File "game/fixBug.rpy", line 22, in script
    player "Hold on-- that's not it."
  File "C:\Users\jayly\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\jayly\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\jayly\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'player' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
datingsim 1.0
Wed May 21 21:31:09 2025
